#!/bin/bash
#Bash Script sent command to all horns to reboot
#HISTORY
#26Apr21 GIL add Reboot
#26Apr13 GIL Initial version

# Create the stop file
FILE="/tmp/NsfReboot"
touch $FILE

scp $FILE radioastro@192.168.1.201:$FILE
scp $FILE radioastro@192.168.1.202:$FILE
scp $FILE radioastro@192.168.1.203:$FILE
scp $FILE radioastro@192.168.1.204:$FILE
scp $FILE radioastro@192.168.1.205:$FILE
scp $FILE radioastro@192.168.1.206:$FILE
scp $FILE radioastro@192.168.1.207:$FILE
scp $FILE radioastro@192.168.1.208:$FILE
scp $FILE radioastro@192.168.1.209:$FILE
scp $FILE radioastro@192.168.1.210:$FILE
scp $FILE radioastro@192.168.1.211:$FILE
scp $FILE radioastro@192.168.1.214:$FILE

