#!/bin/bash
#Bash Script to check for NSF communication Files in the /tmp
#directory and restart observations as needed.
#HISTORY
#26Apr21 GIL Fix Azmuth update
#26Apr13 GIL Initial version

#Must set the Pi home directory for pitools and analyze
export RAHOME=/home/radioastro
export TOOLS=$RAHOME/Research/pitools
export ANALYZE=$RAHOME/Research/analyze

export now=`date -u`

export FILE="/tmp/NsfStop"
if [ -f "$FILE" ]; then
   $TOOLS/NsfStop
   rm $FILE
   echo $now "Stopped Observations" >> /tmp/Update.log
fi

FILE="/tmp/NsfRestart"
if [ -f "$FILE" ]; then
   $TOOLS/NsfRestart
   rm $FILE
   echo $now "Restarted Observations" >> /tmp/Update.log
fi

FILE="/tmp/NsfElevation"
if [ -f "$FILE" ]; then
   echo "Found New Eevation"
   export NewEl=`cat $FILE`
   echo $NewEl
   $TOOLS/NsfStop
   cd $HOME/nsf
   $TOOLS/replaceElevation $NewEl
   rm $FILE
   echo $now "Updated Elevation" >> /tmp/Update.log
fi

FILE="/tmp/NsfAzimuth"
if [ -f "$FILE" ]; then
   export NewAz=`cat $FILE`
   echo $NewAz
   $TOOLS/NsfStop
   $HOME/nsf
   $TOOLS/replaceAzimuth $NewAz
   $TOOLS/NsfRestart
   rm $FILE
   echo $now "Updated Azimuth" >> /tmp/Update.log
fi

