#!/bin/bash
#HISTORY
#21DEC08 GIL enable any user to use this code
#20JUN22 GIL Watch for events
#20JUN17 GIL initialversion that starts up Observations

cd $HOME/Research/gr-radio_astro/examples/nsf
echo "------------------------"
echo "PlutoSDR Radio Astronomy Event Detection; 4.5 MHz bandwidth"
echo "------------------------"

python NsfDetect45.py
