#!/bin/bash
#HISTORY
#21DEC08 GIL enable any user to use this code
#20AUG16 GIL initialversion that starts up Observations

cd $HOME/Research/gr-radio_astro/examples/nsf

echo "------------------------"
echo "AIRSPY Mini Radio Astronomy with 6 MHz bandwidth"
echo "------------------------"
python NsfIntegrate60.py
