#!/bin/bash
#HISTORY
#23Mar27 GIL initial version restart NsfWatch after reboot

export NsfHome=/home/radioastro/Research/gr-radio_astro/examples/nsf
export NsfExec=NsfWatchNoGui80.py
echo "Launching NsfWatch"

echo Going to Directory $NsfHome
cd $NsfHome

# this line executes the command
/usr/bin/python $NsfExec &

echo "Waiting for NsfWatch to start"
sleep 5
echo "Getting NsfWatch PID"
sleep 1
export gidinfo=`ps -ejf | grep 'python' | grep 'NsfWatch' | head -1`
export gid=`echo $gidinfo | awk -v N=3 '{print $N}'`
export gidinfo2=`ps -ejf | grep 'python' | grep 'NsfWatch' | tail -1`
export gid2=`echo $gidinfo2 | awk -v N=3 '{print $N}'`

if [ "$gid" == "" ]
then
   echo "Nsf Watch did not start; Trying again!"
   /usr/bin/python $NsfExec &
   sleep 5
fi

export gidinfo=`ps -ejf | grep 'python' | grep 'NsfWatch' | head -1`
export gid=`echo $gidinfo | awk -v N=3 '{print $N}'`
export gidinfo2=`ps -ejf | grep 'python' | grep 'NsfWatch' | tail -1`
export gid2=`echo $gidinfo2 | awk -v N=3 '{print $N}'`

echo "Re-nicing Group: " $gid 
echo "Re-nicing Group: " $gidinfo

if [ "$gid" == "" ]
then
   echo "Nsf Watch did not start again; Trying a 3rd Time!"
   /usr/bin/python $NsfExec &
   sleep 5
fi

export gidinfo=`ps -ejf | grep 'python' | grep 'NsfWatch' | head -1`
export gid=`echo $gidinfo | awk -v N=3 '{print $N}'`
export gidinfo2=`ps -ejf | grep 'python' | grep 'NsfWatch' | tail -1`
export gid2=`echo $gidinfo2 | awk -v N=3 '{print $N}'`

if [ "$gid" == "" ]
then
   echo "Nsf Watch did not start again; Giving up!"
else 
   sudo renice -n -10 -g $gid

   # sometimes the PID is the last in the list; use tail
   echo "Re-nicing Group " $gid2
   sudo renice -n -10 -g $gid2
fi



