#!/bin/bash
#HISTORY
#21DEC08 GIL enable any user to use this code
#20JUN22 GIL Watch for events
#20JUN17 GIL initialversion that starts up Observations

cd $HOME/Research/gr-radio_astro/examples/nsf
echo "------------------------"
echo "AirSpy Mini Radio Astronomy Spectra with Event Detection; 6.0 MHz bandwidth"
echo "------------------------"

python NsfWatch60.py
