#!/bin/bash
#HISTORY
#21DEC08 GIL enable any user to use this code
#20JUN22 GIL Watch for events
#20JUN17 GIL initialversion that starts up Observations

cd $hOME/Research/gr-radio_astro/examples/nsf
echo "------------------------"
echo "NeSDR Radio Astronomy Spectra with Event Detection; 2.4 MHz bandwidth"
echo "------------------------"

python NsfWatch24.py
