#!/bin/bash
#HISTORY
#20AUG16 GIL Watch for events
#20JUN17 GIL initialversion that starts up Observations

cd /home/pi/Research/gr-radio_astro/examples
echo "------------------------"
echo "AIRSPY Radio Astronomy Spectra with Event Detection; 100 MHz bandwidth"
echo "No GUI is started.  Setup with NsfWatch100"
echo "------------------------"

python NsfWatch100NoGui.py
