#!/bin/bash
#HISTORY
#20JUN22 GIL Watch for events
#20JUN17 GIL initialversion that starts up Observations

cd $HOME/Research/gr-radio_astro/examples/nsf

echo "------------------------"
echo "SDRPlay (RSP1A) Radio Astronomy Spectra with Event Detection; 8.0 MHz bandwidth"
echo "------------------------"

python NsfWatch80.py

