#!/bin/bash
#Bash Script to update the GnurRadio Configuration files and 
#RadioAstro Note files for new telescope position
#HISTORY
#26Apr21 GIL update note files for new position
#26Apr13 GIL Initial version

if [ $# -eq 0 ]; then
    echo "Must provide an Elevation (in degrees)"
    exit -1
fi

export NewEl=$1
# go to where the config files are

cd ~/nsf

# Define the extension
EXT="conf"

# Loop through matching files
for file in *."$EXT"; do
    # Check if files exist to avoid errors
    [ -e "$file" ] || continue
    
    echo "Processing $file..."
    sed -i "s/^\(elevation[[:space:]]*=[[:space:]]*\).*/\1$NewEl/" $file
done

echo "Updating Note files for new Elevation:" $NewEl

$HOME/Research/analyze/FIX -RE -EL $NewEl *.not

